# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    test: true
    session:
        storage_factory_id: session.storage.factory.mock_file
    profiler:
        collect: false

parameters:
    stripe.test_mode: true
    stripe.test_cards:
        success: '4242424242424242'
        failure: '4000000000000002'
        three_d_secure: '4000000000003220'