security:
    # Configuration des algorithmes de hachage pour les mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration des providers pour récupérer les utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            stateless: false
            
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
                enable_csrf: true
            
            logout:
                path: app_logout
                target: app_login
            
            # Entry point pour déterminer la méthode d'authentification par défaut
            entry_point: form_login

            # Configuration de la fonctionnalité "Se souvenir de moi"
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # Uncomment the following line to always enable remember me
                #always_remember_me: true

    # Contrôle d'accès basé sur les rôles
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/cart, roles: ROLE_USER }
        - { path: ^/products, roles: ROLE_USER }
        - { path: ^/product, roles: ROLE_USER }
        

# Configuration spécifique pour l'environnement "test"
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
